### ISSUE TITLE
fail to install signatory

### ISSUE THREAD

**Issue by yantijin** [patrick-kidger/signatory#34]
When I try to install signatory on linux as `pip install -U signatory-1.2.3.1.4.0 --no-cache-dir --force-reinstall`, It builds wheel faild, and the error list is so long. When I try to clone and install from source, it also failed. Here is the version of its dependencies:
gcc 9.2.0
python: 3.6.7
torch: 1.4.0
What can I do to fix this?

**Comment by patrick-kidger** [comment]
I'd start by noting that the command you've given won't work because it should be `signatory==1.2.3.1.4.0`, not `signatory-1.2.3.1.4.0`.

That aside, things work for me with Ubuntu, **gcc 7.5.0**, Python 3.6.7, PyTorch 1.4.0.

You could try using this previous version of GCC, although I'm doubtful that that will be the reason. If you can provide the error message (large as it may be) then that will help dramatically.

**Comment by yantijin** [comment]
> I'd start by noting that the command you've given won't work because it should be `signatory==1.2.3.1.4.0`, not `signatory-1.2.3.1.4.0`.
> 
> That aside, things work for me with Ubuntu, **gcc 7.5.0**, Python 3.6.7, PyTorch 1.4.0.
> 
> You could try using this previous version of GCC, although I'm doubtful that that will be the reason. If you can provide the error message (large as it may be) then that will help dramatically.

Oh. I's soryy, that's a typo. I did follow the command in readme and it failed.  And here is the log file for installing signatory.
[logs.txt](https://github.com/patrick-kidger/signatory/files/5401993/logs.txt)

**Comment by patrick-kidger** [comment]
So it looks like your installation is a bit strange, as it's complaining about `site-packages` not being writeable, needing temp directories, and so on. That's probably not helping things.

Can you try this with the version of GCC I specified and tell me if that changes anything?

Ultimately this doesn't look like a Signatory issue - judging by the logs, your computer/compiler setup isn't happy compiling PyTorch itself.
